language: python
sudo: false
python:
  - "2.7"
  
cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install -q -r requirements.txt
#  - python setup.py -q install

script:
  - python --version
  - pylint nimbuspi --rcfile=.pylintrc
  - pylint nimbuspi/tests/steps/*.py --rcfile=.pylintrc
  - behave nimbuspi/tests/

#after_failure:
#  - echo "FAILURE DETAILS (from XML reports):"
#  - bin/behave.junit_filter.py --status=failed reports
